libnetmd: libnetmd.h File Reference
libnetmd.h File Reference
#include <usb.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <errno.h>
Data Structures
struct netmd_devices
Struct to hold the vendor and product id's for each unit.
struct netmd_group
Data about a group, start track, finish track and name.
struct netmd_track
Basic track data.
struct netmd_pair
stores hex value from protocol and text value of name
struct minidisc
stores misc data for a minidisc
Defines
#define NETMDERR_USB -1
Error codes of the USB transport layer.
#define NETMDERR_NOTREADY -2
#define NETMDERR_TIMEOUT -3
#define NETMDERR_CMD_FAILED -4
#define NETMDERR_CMD_INVALID -5
Typedefs
typedef struct netmd_group netmd_group_t
Data about a group, start track, finish track and name.
typedef struct netmd_pair netmd_pair_t
stores hex value from protocol and text value of name
Functions
void print_hex (unsigned char *buf, size_t size)
Utility function for checking data.
struct netmd_pair const * find_pair (int hex, struct netmd_pair const *pair)
enum through an array of pairs looking for a specific hex code.
struct usb_device * netmd_init ()
used internally to get the size of buffer needed for the returning data.
usb_dev_handle * netmd_open (struct usb_device *dev)
int netmd_get_devname (usb_dev_handle *dev, unsigned char *buf, int buffsize)
int netmd_exch_message (usb_dev_handle *dev, unsigned char *cmd, int cmdlen, unsigned char *rsp)
int netmd_request_track_codec (usb_dev_handle *dev, int track, char *data)
int netmd_request_track_bitrate (usb_dev_handle *dev, int track, unsigned char *data)
int netmd_request_title (usb_dev_handle *dev, int track, char *buffer, int size)
int netmd_request_track_time (usb_dev_handle *dev, int track, struct netmd_track *buffer)
int netmd_set_title (usb_dev_handle *dev, int track, char *buffer, int size)
int netmd_set_group_title (usb_dev_handle *dev, minidisc *md, int group, char *title)
int netmd_move_track (usb_dev_handle *dev, int start, int finish)
int netmd_initialize_disc_info (usb_dev_handle *dev, minidisc *md)
int netmd_create_group (usb_dev_handle *devh, char *name)
int netmd_write_disc_header (usb_dev_handle *devh, minidisc *md)
int netmd_put_track_in_group (usb_dev_handle *dev, minidisc *md, int track, int group)
int netmd_move_group (usb_dev_handle *dev, minidisc *md, int track, int group)
int netmd_delete_group (usb_dev_handle *dev, minidisc *md, int group)
int netmd_set_track (usb_dev_handle *dev, int track)
int netmd_play (usb_dev_handle *dev)
int netmd_stop (usb_dev_handle *dev)
int netmd_pause (usb_dev_handle *dev)
int netmd_rewind (usb_dev_handle *dev)
int netmd_fast_forward (usb_dev_handle *dev)
int netmd_delete_track (usb_dev_handle *dev, int track)
int netmd_secure_cmd_80 (usb_dev_handle *dev)
Start secure session?
int netmd_secure_cmd_11 (usb_dev_handle *dev, unsigned int *player_id)
Get 4-byte player ID?
int netmd_secure_cmd_12 (usb_dev_handle *dev, unsigned char *ekb_head, unsigned char *ekb_body)
Send 40-byte EKB (enabling key block)?
int netmd_secure_cmd_20 (usb_dev_handle *dev, unsigned char *rand_in, unsigned char *rand_out)
Exchange 8-byte random?
int netmd_secure_cmd_21 (usb_dev_handle *dev)
Discard random?
int netmd_secure_cmd_81 (usb_dev_handle *dev)
End secure session?
int netmd_secure_cmd_22 (usb_dev_handle *dev, unsigned char *hash)
Send 32-byte hash?
int netmd_secure_cmd_28 (usb_dev_handle *dev, unsigned int track_type, unsigned int length_byte, unsigned int length, unsigned int *track_nr)
Prepare USB download?
int netmd_secure_cmd_48 (usb_dev_handle *dev, unsigned int track_nr, unsigned char *hash)
Verify track with 8-byte hash?
int netmd_secure_cmd_23 (usb_dev_handle *dev, unsigned int track_nr, unsigned char *hash_id)
Get 8-byte hash id of a track?
int netmd_secure_cmd_40 (usb_dev_handle *dev, unsigned int track_nr, unsigned char *signature)
Secure delete with 8-byte signature?
int netmd_write_track (usb_dev_handle *dev, char *szFile)
void netmd_clean_disc_info (minidisc *md)
void netmd_clean (usb_dev_handle *dev)
void test (usb_dev_handle *dev)
float netmd_get_playback_position (usb_dev_handle *dev)
int netmd_get_current_track (usb_dev_handle *dev)
Variables
struct netmd_group * groups
Global variable containing netmd_group data for each group There will be enough for group_count total in the alloced memory.
struct netmd_pair const codecs []
struct netmd_pair const bitrates []
struct netmd_pair const unknown_pair
Define Documentation
#define NETMDERR_CMD_FAILED -4
Definition at line 35 of file libnetmd.h.
#define NETMDERR_CMD_INVALID -5
Definition at line 36 of file libnetmd.h.
#define NETMDERR_NOTREADY -2
Definition at line 33 of file libnetmd.h.
Referenced by netmd_exch_message().
#define NETMDERR_TIMEOUT -3
Definition at line 34 of file libnetmd.h.
Referenced by netmd_exch_message().
#define NETMDERR_USB -1
Error codes of the USB transport layer.
Definition at line 32 of file libnetmd.h.
Referenced by netmd_exch_message().
Typedef Documentation
typedef struct netmd_group netmd_group_t
Data about a group, start track, finish track and name.
Used to generate disc header info.
typedef struct netmd_pair netmd_pair_t
stores hex value from protocol and text value of name
Function Documentation
struct netmd_pair const* find_pair (int hex, struct netmd_pair const * pair) [read]
enum through an array of pairs looking for a specific hex code.
Parameters:
hex hex code to find. array of pairs to look through.
Definition at line 116 of file libnetmd.c.
References netmd_pair::name.
Referenced by print_disc_info().
void netmd_clean (usb_dev_handle * dev)
closes the usb descriptors
Parameters:
dev pointer to device returned by netmd_open
Definition at line 1508 of file libnetmd.c.
Referenced by main().
void netmd_clean_disc_info (minidisc * md)
Cleans memory allocated for the name of each group, then cleans groups pointer
Parameters:
md pointer to minidisc structure
Definition at line 1494 of file libnetmd.c.
References minidisc::group_count, minidisc::groups, and netmd_group::name.
Referenced by main(), netmd_delete_group(), and netmd_move_group().
int netmd_create_group (usb_dev_handle * devh, char * name)
Definition at line 715 of file libnetmd.c.
References netmd_exch_message().
Referenced by main().
int netmd_delete_group (usb_dev_handle * dev, minidisc * md, int group)
Deletes group from disc (but not the tracks in it)
Parameters:
dev pointer to device returned by netmd_open
md pointer to minidisc structure
track Zero based track to delete
Definition at line 995 of file libnetmd.c.
References netmd_group::finish, minidisc::group_count, minidisc::groups, netmd_group::name, netmd_clean_disc_info(), netmd_write_disc_header(), and netmd_group::start.
Referenced by main().
int netmd_delete_track (usb_dev_handle * dev, int track)
Definition at line 1436 of file libnetmd.c.
References netmd_exch_message().
Referenced by main().
int netmd_exch_message (usb_dev_handle * dev, unsigned char * cmd, int cmdlen, unsigned char * rsp)
Function for internal use by init_disc_info
Function to exchange command/response buffer with minidisc
Parameters:
dev device handle
cmd command buffer
cmdlen length of command
rsp response buffer
Returns:
number of bytes received if >0, or error if <0
Definition at line 171 of file libnetmd.c.
References NETMD_RECV_TIMEOUT, NETMD_RECV_TRIES, NETMD_SEND_TIMEOUT, NETMDERR_NOTREADY, NETMDERR_TIMEOUT, and NETMDERR_USB.
Referenced by netmd_create_group(), netmd_delete_track(), netmd_get_current_track(), netmd_get_playback_position(), netmd_move_track(), netmd_request_title(), netmd_request_track_bitrate(), netmd_request_track_codec(), netmd_request_track_time(), netmd_set_title(), netmd_set_track(), netmd_stop(), and netmd_write_disc_header().
int netmd_fast_forward (usb_dev_handle * dev)
Definition at line 1102 of file libnetmd.c.
References NETMD_FFORWARD.
Referenced by main().
int netmd_get_current_track (usb_dev_handle * dev)
gets the currently playing track
Parameters:
dev pointer to device returned by netmd_open
Definition at line 1448 of file libnetmd.c.
References netmd_exch_message().
Referenced by print_current_track_info().
int netmd_get_devname (usb_dev_handle * dev, unsigned char * buf, int buffsize)
Get the device name stored in USB device
Parameters:
dev pointer to device returned by netmd_open
buf buffer to hold the name.
buffsize of buf.
Returns:
Actual size of buffer, if your buffer is too small resize buffer and recall function.
Definition at line 311 of file libnetmd.c.
Referenced by main().
float netmd_get_playback_position (usb_dev_handle * dev)
gets the position within the currently playing track in seconds.hundreds
Parameters:
dev pointer to device returned by netmd_open
Definition at line 1465 of file libnetmd.c.
References BCD_TO_PROPER, and netmd_exch_message().
Referenced by print_current_track_info().
struct usb_device* netmd_init () [read]
used internally to get the size of buffer needed for the returning data.
Parameters:
dev USB device handle.
Returns:
size of buffer to alloc. Finds netmd device and returns pointer to its device handle
Definition at line 273 of file libnetmd.c.
References netmd_devices::idProduct, and netmd_devices::idVendor.
Referenced by main().
int netmd_initialize_disc_info (usb_dev_handle * dev, minidisc * md)
used internally - use the int group_count var.
Parameters:
dev pointer to device returned by netmd_open
md pointer to minidisc structure
Returns:
Number of groups, counting disc title as a group (which it is)
sets up buffer containing group info.
Parameters:
dev pointer to device returned by netmd_open
md pointer to minidisc structure
Returns:
total size of disc header Group[0] is disc name. You need to make sure you call clean_disc_info before recalling
Definition at line 592 of file libnetmd.c.
References minidisc::group_count, minidisc::groups, and minidisc::header_length.
Referenced by main().
int netmd_move_group (usb_dev_handle * dev, minidisc * md, int track, int group)
Moves group around the disc.
Parameters:
dev pointer to device returned by netmd_open
md pointer to minidisc structure
track Zero based track to make group start at.
group number of group (0 is title group).
Definition at line 906 of file libnetmd.c.
References netmd_group::finish, minidisc::group_count, groups, minidisc::groups, netmd_group::name, netmd_clean_disc_info(), netmd_move_track(), netmd_write_disc_header(), and netmd_group::start.
Referenced by main().
int netmd_move_track (usb_dev_handle * dev, int start, int finish)
Moves track around the disc.
Parameters:
dev pointer to device returned by netmd_open
start Zero based index of track to move
finish Zero based track to make it
Returns:
0 for fail 1 for success
Definition at line 491 of file libnetmd.c.
References netmd_exch_message().
Referenced by main(), netmd_move_group(), and netmd_put_track_in_group().
usb_dev_handle* netmd_open (struct usb_device * dev)
Initialize USB subsystem for talking to NetMD
Parameters:
dev Pointer returned by netmd_init.
Definition at line 302 of file libnetmd.c.
Referenced by main().
int netmd_pause (usb_dev_handle * dev)
Definition at line 1095 of file libnetmd.c.
References NETMD_PAUSE.
Referenced by main().
int netmd_play (usb_dev_handle * dev)
Definition at line 1088 of file libnetmd.c.
References NETMD_PLAY.
Referenced by main().
int netmd_put_track_in_group (usb_dev_handle * dev, minidisc * md, int track, int group)
Moves track into group
Parameters:
dev pointer to device returned by netmd_open
md pointer to minidisc structure
track Zero based track to add to group.
group number of group (0 is title group).
Definition at line 786 of file libnetmd.c.
References netmd_group::finish, minidisc::group_count, minidisc::groups, netmd_move_track(), netmd_write_disc_header(), print_groups(), and netmd_group::start.
Referenced by main().
int netmd_request_title (usb_dev_handle * dev, int track, char * buffer, int size)
Get the title for a specific track.
Parameters:
dev pointer to device returned by netmd_open
track Zero based index of track your requesting.
buffer buffer to hold the name.
size of buf.
Returns:
Actual size of buffer, if your buffer is too small resize buffer and recall function.
Definition at line 430 of file libnetmd.c.
References netmd_exch_message().
Referenced by print_current_track_info(), and print_disc_info().
int netmd_request_track_bitrate (usb_dev_handle * dev, int track, unsigned char * data)
Get the bitrate used to encode a specific track.
Parameters:
dev pointer to device returned by netmd_open
track Zero based index of track your requesting.
data pointer to store the hex code representing the bitrate.
Definition at line 354 of file libnetmd.c.
References netmd_exch_message().
Referenced by print_disc_info().
int netmd_request_track_codec (usb_dev_handle * dev, int track, char * data)
Get the codec used to encode a specific track.
Parameters:
dev pointer to device returned by netmd_open
track Zero based index of track your requesting.
data pointer to store the hex code representing the codec.
Definition at line 378 of file libnetmd.c.
References netmd_exch_message().
Referenced by print_disc_info().
int netmd_request_track_time (usb_dev_handle * dev, int track, struct netmd_track * buffer)
Definition at line 405 of file libnetmd.c.
References BCD_TO_PROPER, netmd_track::minute, netmd_exch_message(), netmd_track::second, netmd_track::tenth, and netmd_track::track.
Referenced by print_disc_info().
int netmd_rewind (usb_dev_handle * dev)
Definition at line 1109 of file libnetmd.c.
References NETMD_REWIND.
Referenced by main().
int netmd_secure_cmd_11 (usb_dev_handle * dev, unsigned int * player_id)
Get 4-byte player ID?
Definition at line 70 of file libnetmd_secure.c.
References SECURE_CMD_HDR.
int netmd_secure_cmd_12 (usb_dev_handle * dev, unsigned char * ekb_head, unsigned char * ekb_body)
Send 40-byte EKB (enabling key block)?
Definition at line 89 of file libnetmd_secure.c.
References SECURE_CMD_HDR.
int netmd_secure_cmd_20 (usb_dev_handle * dev, unsigned char * rand_in, unsigned char * rand_out)
Exchange 8-byte random?
Definition at line 112 of file libnetmd_secure.c.
References SECURE_CMD_HDR.
int netmd_secure_cmd_21 (usb_dev_handle * dev)
Discard random?
Definition at line 136 of file libnetmd_secure.c.
References SECURE_CMD_HDR.
int netmd_secure_cmd_22 (usb_dev_handle * dev, unsigned char * hash)
Send 32-byte hash?
Definition at line 160 of file libnetmd_secure.c.
References SECURE_CMD_HDR.
int netmd_secure_cmd_23 (usb_dev_handle * dev, unsigned int track_nr, unsigned char * hash_id)
Get 8-byte hash id of a track?
Definition at line 241 of file libnetmd_secure.c.
References SECURE_CMD_HDR.
int netmd_secure_cmd_28 (usb_dev_handle * dev, unsigned int track_type, unsigned int length_byte, unsigned int length, unsigned int * track_nr)
Prepare USB download?
Parameters:
dev USB device handle
track_type SP=0x006, LP2=0x9402, LP4=0xA800
length_byte ??? 0x58 and 0x5A have been seen here
length length of USB download
*track_nr new track number
Definition at line 184 of file libnetmd_secure.c.
References SECURE_CMD_HDR.
int netmd_secure_cmd_40 (usb_dev_handle * dev, unsigned int track_nr, unsigned char * signature)
Secure delete with 8-byte signature?
Parameters:
dev USB device handle
track_nr track number to delete?
signature 8-byte signature of deleted track
Definition at line 268 of file libnetmd_secure.c.
References SECURE_CMD_HDR.
int netmd_secure_cmd_48 (usb_dev_handle * dev, unsigned int track_nr, unsigned char * hash)
Verify track with 8-byte hash?
Definition at line 217 of file libnetmd_secure.c.
References SECURE_CMD_HDR.
int netmd_secure_cmd_80 (usb_dev_handle * dev)
Start secure session?
Definition at line 60 of file libnetmd_secure.c.
References SECURE_CMD_HDR.
int netmd_secure_cmd_81 (usb_dev_handle * dev)
End secure session?
Definition at line 146 of file libnetmd_secure.c.
References SECURE_CMD_HDR.
int netmd_set_group_title (usb_dev_handle * dev, minidisc * md, int group, char * title)
Sets title for the specified track.
Parameters:
dev pointer to device returned by netmd_open
md pointer to minidisc structure
group Zero based index of group your renaming (zero is disc title).
title buffer holding the name.
Returns:
returns 0 for fail 1 for success.
Definition at line 558 of file libnetmd.c.
References minidisc::groups, netmd_group::name, and netmd_write_disc_header().
Referenced by main().
int netmd_set_title (usb_dev_handle * dev, int track, char * buffer, int size)
Sets title for the specified track.
Parameters:
dev pointer to device returned by netmd_open
track Zero based index of track your requesting.
buffer buffer to hold the name.
size of buf.
Returns:
returns 0 for fail 1 for success.
Definition at line 463 of file libnetmd.c.
References netmd_exch_message().
Referenced by import_m3u_playlist(), main(), and netmd_write_track().
int netmd_set_track (usb_dev_handle * dev, int track)
Definition at line 1032 of file libnetmd.c.
References netmd_exch_message().
Referenced by main().
int netmd_stop (usb_dev_handle * dev)
Definition at line 1116 of file libnetmd.c.
References netmd_exch_message().
Referenced by main().
int netmd_write_disc_header (usb_dev_handle * devh, minidisc * md)
Creates disc header out of groups and writes it to disc
Parameters:
dev pointer to device returned by netmd_open
md pointer to minidisc structure
Definition at line 1140 of file libnetmd.c.
References netmd_group::finish, minidisc::group_count, minidisc::groups, minidisc::header_length, netmd_group::name, netmd_exch_message(), and netmd_group::start.
Referenced by main(), netmd_delete_group(), netmd_move_group(), netmd_put_track_in_group(), and netmd_set_group_title().
int netmd_write_track (usb_dev_handle * dev, char * szFile)
Writes atrac file to device
Parameters:
dev pointer to device returned by netmd_open
szFile Full path to file to write.
Returns:
< 0 on fail else 1
Bug:
doesnt work yet
Definition at line 1258 of file libnetmd.c.
References min(), netmd_set_title(), and print_hex().
Referenced by main().
void print_hex (unsigned char * buf, size_t size)
Utility function for checking data.
Parameters:
buf buffer to print.
size length of buffer to print.
Definition at line 69 of file libnetmd.c.
Referenced by netmd_write_track().
void test (usb_dev_handle * dev)
testing function for testing weird unknown commands
Definition at line 1515 of file libnetmd.c.
Referenced by main().
Variable Documentation
struct netmd_pair const bitrates[]
list of known bitrates (mapped to protocol ID) that can be used in NetMD devices
Definition at line 59 of file libnetmd.c.
Referenced by print_disc_info().
struct netmd_pair const codecs[]
list of known codecs (mapped to protocol ID) that can be used in NetMD devices
Definition at line 51 of file libnetmd.c.
Referenced by print_disc_info().
struct netmd_group* groups
Global variable containing netmd_group data for each group There will be enough for group_count total in the alloced memory.
Referenced by netmd_move_group().
struct netmd_pair const unknown_pair
Definition at line 67 of file libnetmd.c.