libnetmd: netmd.c File Reference
netmd.c File Reference
#include "libnetmd.h"
Defines
#define M3U_LINE_MAX 128
Functions
void print_disc_info (usb_dev_handle *devh, minidisc *md)
void print_current_track_info (usb_dev_handle *devh)
void print_syntax ()
void import_m3u_playlist (usb_dev_handle *devh, const char *file)
int main (int argc, char *argv[])
Define Documentation
#define M3U_LINE_MAX 128
Definition at line 28 of file netmd.c.
Referenced by import_m3u_playlist().
Function Documentation
void import_m3u_playlist (usb_dev_handle * devh, const char * file)
Definition at line 367 of file netmd.c.
References M3U_LINE_MAX, netmd_set_title(), and print_syntax().
Referenced by main().
int main (int argc, char * argv[])
Definition at line 100 of file netmd.c.
References netmd_group::finish, minidisc::groups, import_m3u_playlist(), netmd_group::name, netmd_clean(), netmd_clean_disc_info(), netmd_create_group(), netmd_delete_group(), netmd_delete_track(), netmd_fast_forward(), netmd_get_devname(), netmd_init(), netmd_initialize_disc_info(), netmd_move_group(), netmd_move_track(), netmd_open(), netmd_pause(), netmd_play(), netmd_put_track_in_group(), netmd_rewind(), netmd_set_group_title(), netmd_set_title(), netmd_set_track(), netmd_stop(), netmd_write_disc_header(), netmd_write_track(), print_current_track_info(), print_disc_info(), print_syntax(), netmd_group::start, and test().
void print_current_track_info (usb_dev_handle * devh)
Definition at line 262 of file netmd.c.
References netmd_get_current_track(), netmd_get_playback_position(), and netmd_request_title().
Referenced by main().
void print_disc_info (usb_dev_handle * devh, minidisc * md)
Definition at line 286 of file netmd.c.
References bitrates, codecs, find_pair(), netmd_group::finish, minidisc::group_count, minidisc::groups, netmd_track::minute, netmd_pair::name, netmd_group::name, netmd_request_title(), netmd_request_track_bitrate(), netmd_request_track_codec(), netmd_request_track_time(), netmd_track::second, netmd_group::start, and netmd_track::tenth.
Referenced by main().
void print_syntax ()
Definition at line 460 of file netmd.c.
Referenced by import_m3u_playlist(), and main().